name: seeds
description: SEEDS Wallet

version: 1.4.2+32

environment:
  sdk: '>=2.12.0 <3.0.0'

analyzer:
  enable-experiment: extension-methods

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  url_launcher: ^6.0.3
  step_progress_indicator: ^1.0.0-nullsafety.0
  uni_links: ^0.5.1
  intro_views_flutter: ^3.0.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^4.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0
  local_auth: ^1.1.1
  timeago: ^3.0.2
  cached_network_image: ^3.0.0
  passcode_screen: ^2.0.0
  percent_indicator: ^3.0.1
  flutter_svg: ^0.22.0
  firebase_dynamic_links: ^2.0.7
  firebase_messaging: ^10.0.0
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  cloud_firestore: ^2.2.1
  firebase_remote_config: ^0.10.0+1
  liquid_pull_to_refresh: ^3.0.0
  shimmer: ^2.0.0
  share: ^2.0.1
  provider: ^5.0.0
  photo_view: ^0.11.1
  image_cropper: ^1.2.1
  carousel_slider: ^4.0.0-nullsafety.0
  dots_indicator: ^2.0.0
  permission_handler: ^8.0.1
  qr_flutter: ^4.0.0
  image_picker: ^0.8.2
  oktoast: ^3.0.0
  eosdart:
    git: 
      url: https://github.com/JoinSEEDS/eosdart.git
      ref: flutter_2_nns
  dart_esr:
    git:
      url: https://github.com/JoinSEEDS/dart-esr.git
      ref: flutter_2_nns
      
  webview_flutter: ^2.0.2
  rubber: ^1.0.0
  path_provider: ^2.0.1
  dotted_border: ^2.0.0-nullsafety.0
  pedantic: ^1.9.2
  flutter_pagewise: ^2.0.1
  qr_code_scanner: ^0.4.0
  collection: ^1.15.0-nullsafety.4
  mask_text_input_formatter: ^2.0.0
  lottie: ^1.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^5.0.7

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/ecosystem.svg
    - assets/images/app_icon.png
    - assets/images/seeds_currency_icon.svg
    - assets/images/app_icon_transparent.png
    - assets/images/loading.png
    - assets/images/seeds_symbol_forest.png
    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png
    - assets/images/onboarding/onboarding4.png
    - assets/images/onboarding/onboarding5.png
    - assets/images/onboarding/leaves/pointing_left/medium_dark_leaf.svg
    - assets/images/onboarding/leaves/pointing_left/medium_light_leaf.svg
    - assets/images/onboarding/leaves/pointing_left/small_light_leaf.svg
    - assets/images/onboarding/leaves/pointing_right/big_dark_leaf.svg
    - assets/images/onboarding/leaves/pointing_right/big_light_leaf.svg
    - assets/images/onboarding/leaves/pointing_right/small_light_leaf.svg
    - assets/images/governance.svg
    - assets/images/community.svg
    - assets/images/harvest.svg
    - assets/images/exchange.svg
    - assets/images/ecosystem.svg
    - assets/images/wallet.svg
    - assets/images/profile.svg
    - assets/images/logout.svg
    - assets/images/lotus_support_small.svg
    - assets/images/lotus_support_big.svg
    - assets/images/seeds.png
    - assets/images/appbar/seeds_symbol_forest.png
    - assets/images/seeds_light_wallet_logo.png
    - assets/images/guardians/guardian_tutorial_1.png
    - assets/images/guardians/guardian_tutorial_2.png
    - assets/images/guardians/guardian_tutorial_3.png
    - assets/images/guardians/guardian_tutorial_4.png
    - assets/images/guardians/invite_guardian_mail.svg
    - assets/images/guardians/check_circle.png
    - assets/images/guardians/invite_guardian_mail.png
    - assets/images/guardians/guardian_shield.png
    - assets/images/guardians/onboarding/onboarding_1.jpg
    - assets/images/guardians/onboarding/onboarding_2.jpg
    - assets/images/guardians/onboarding/onboarding_3.jpg
    - assets/images/guardians/onboarding/onboarding_4.jpg
    - assets/images/navigation_bar/explore.svg
    - assets/images/navigation_bar/wallet.svg
    - assets/images/navigation_bar/user_profile.svg
    - assets/images/navigation_bar/explore_selected.svg
    - assets/images/navigation_bar/wallet_selected.svg
    - assets/images/navigation_bar/user_profile_selected.svg
    - assets/images/explore/hypha_dho_card.jpg
    - assets/images/explore/get_seeds_card.jpg
    - assets/images/wallet/arrow_up.svg
    - assets/images/wallet/arrow_down.svg
    - assets/images/wallet/app_bar/appbar_icon.svg
    - assets/images/wallet/app_bar/scan_qr_code_icon.svg
    - assets/images/wallet/app_bar/appbar_seeds_text.svg
    - assets/images/wallet/currency_info_cards/seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/seeds/background.jpg
    - assets/images/wallet/currency_info_cards/planted_seeds/background.jpg
    - assets/images/wallet/currency_info_cards/planted_seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/hypha/background.jpg
    - assets/images/wallet/currency_info_cards/hypha/logo.jpg
    - assets/images/profile/lotus.svg
    - assets/images/profile/logout_icon.svg
    - assets/images/security/key_guardians_icon.svg
    - assets/images/security/success_outlined_icon.svg
    - assets/images/citizenship/reputation.svg
    - assets/images/citizenship/community.svg
    - assets/images/citizenship/planted.svg
    - assets/images/citizenship/age.svg
    - assets/images/citizenship/transaction.svg
    - assets/images/contribution/reputation.svg
    - assets/images/contribution/community.svg
    - assets/images/contribution/planted.svg
    - assets/images/contribution/transaction.svg
    - assets/images/seeds_logo.svg
    - assets/images/login/background.png
    - assets/images/login/seeds_light_wallet_logo.svg
    - assets/images/receive/receive_input_seeds.svg
    - assets/images/receive/merchant.svg
    - assets/images/currency_switch_button.svg
    - assets/images/transfer/seeds_icon.svg
    - assets/images/transfer/arrow_up.svg
    - assets/animations/forest.json
    - assets/animations/send_animation.json
    # assets end

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick

    #DEPRECATED - DO NOT USE (worksans)
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay/SFProDisplay-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SFProDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Black.ttf
          weight: 900
