name: seeds
description: SEEDS Wallet

version: 2.9.310+10

environment:
  sdk: '>=2.17.0 <3.0.0'

analyzer:
  enable-experiment: extension-methods

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  url_launcher: ^6.1.0
  step_progress_indicator: ^1.0.1
  uni_links: ^0.5.1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^5.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.9
  flutter_secure_storage: ^5.0.2
  local_auth: ^2.0.1
  timeago: ^3.1.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.0.3
  firebase_dynamic_links: ^3.0.1
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  cloud_firestore: ^3.1.0
  firebase_remote_config: ^0.11.0+2
  firebase_analytics: ^9.3.0
  geoflutterfire: ^3.0.2
  shimmer: ^2.0.0
  share: ^2.0.4
  image_cropper: ^2.0.3 
  carousel_slider: ^4.0.0
  qr_flutter: ^4.0.0
  image_picker: ^0.8.5+3
  qr_code_scanner: ^1.0.1
  collection: ^1.15.0
  mask_text_input_formatter: ^2.0.0
  lottie: ^1.2.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  palette_generator: ^0.3.2
  webview_flutter: ^3.0.0
  in_app_review: ^2.0.3
  json_annotation: ^4.4.0
  bs58check: ^1.0.2
  pointycastle: ^3.4.0
  hdkey: ^0.0.1
  package_info_plus: ^1.3.0
  flutterfire_installations: ^0.1.0
  google_maps_flutter: ^2.1.1
  geolocator: ^8.2.0
  geocoding: ^2.0.2
  permission_handler: ^9.2.0
  json_schema2: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^5.0.7
  lint: ^1.7.2
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/ecosystem.svg
    - assets/images/app_icon.png
    - assets/images/seeds_currency_icon.svg
    - assets/images/app_icon_transparent.png
    - assets/images/loading.png
    - assets/images/seeds_symbol_forest.png
    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png
    - assets/images/onboarding/onboarding4.png
    - assets/images/onboarding/onboarding5.png
    - assets/images/onboarding/leaves/pointing_left/medium_dark_leaf.svg
    - assets/images/onboarding/leaves/pointing_left/medium_light_leaf.svg
    - assets/images/onboarding/leaves/pointing_left/small_light_leaf.svg
    - assets/images/onboarding/leaves/pointing_right/big_dark_leaf.svg
    - assets/images/onboarding/leaves/pointing_right/big_light_leaf.svg
    - assets/images/onboarding/leaves/pointing_right/small_light_leaf.svg
    - assets/images/community.svg
    - assets/images/governance.svg
    - assets/images/harvest.svg
    - assets/images/exchange.svg
    - assets/images/ecosystem.svg
    - assets/images/wallet.svg
    - assets/images/profile.svg
    - assets/images/logout.svg
    - assets/images/lotus_support_small.svg
    - assets/images/lotus_support_big.svg
    - assets/images/seeds.png
    - assets/images/appbar/seeds_symbol_forest.png
    - assets/images/seeds_light_wallet_logo.png
    - assets/images/guardians/guardian_tutorial_1.png
    - assets/images/guardians/guardian_tutorial_2.png
    - assets/images/guardians/guardian_tutorial_3.png
    - assets/images/guardians/guardian_tutorial_4.png
    - assets/images/guardians/invite_guardian_mail.svg
    - assets/images/guardians/check_circle.png
    - assets/images/guardians/invite_guardian_mail.png
    - assets/images/guardians/guardian_shield.png
    - assets/images/guardians/onboarding/onboarding_1.jpg
    - assets/images/guardians/onboarding/onboarding_2.jpg
    - assets/images/guardians/onboarding/onboarding_3.jpg
    - assets/images/guardians/onboarding/onboarding_4.jpg
    - assets/images/navigation_bar/explore.svg
    - assets/images/navigation_bar/wallet.svg
    - assets/images/navigation_bar/user_profile.svg
    - assets/images/navigation_bar/explore_selected.svg
    - assets/images/navigation_bar/wallet_selected.svg
    - assets/images/navigation_bar/user_profile_selected.svg
    - assets/images/explore/hypha_dho_card.jpg
    - assets/images/explore/get_seeds_card.png
    - assets/images/explore/delegate.svg
    - assets/images/explore/marker_location.svg
    - assets/images/explore/introducing_delegate.png
    - assets/images/explore/swap_leaves_left.png
    - assets/images/explore/swap_leaves_rigth.png
    - assets/images/wallet/arrow_up.svg
    - assets/images/wallet/share_transaction_id.svg
    - assets/images/wallet/leaves_bttm_left.png
    - assets/images/wallet/leaves_bttm_right.png
    - assets/images/wallet/arrow_down.svg
    - assets/images/wallet/app_bar/appbar_icon.svg
    - assets/images/wallet/app_bar/scan_qr_code_icon.svg
    - assets/images/wallet/app_bar/appbar_seeds_text.svg
    - assets/images/wallet/currency_info_cards/seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/husd/logo.jpg
    - assets/images/wallet/currency_info_cards/husd/background.jpg
    - assets/images/wallet/currency_info_cards/seeds/background.jpg
    - assets/images/wallet/currency_info_cards/lscl/background.jpg
    - assets/images/wallet/currency_info_cards/lscl/logo.png
    - assets/images/wallet/currency_info_cards/planted_seeds/background.jpg
    - assets/images/wallet/currency_info_cards/planted_seeds/logo.jpg
    - assets/images/wallet/currency_info_cards/hypha/background.jpg
    - assets/images/wallet/currency_info_cards/hypha/logo.jpg
    - assets/images/wallet/currency_info_cards/stars/background.jpg
    - assets/images/wallet/currency_info_cards/stars/logo.jpg
    - assets/images/wallet/currency_info_cards/tlos/background.png
    - assets/images/wallet/currency_info_cards/tlos/logo.png
    - assets/images/wallet/currency_info_cards/seeds/seeds_check_transp.png
    - assets/images/wallet/currency_info_cards/experimental.png
    - assets/images/profile/lotus.svg
    - assets/images/profile/logout_icon.svg
    - assets/images/profile/contribution_icon.svg
    - assets/images/profile/celebration_icon.png
    - assets/images/security/key_guardians_icon.svg
    - assets/images/security/success_outlined_icon.svg
    - assets/images/citizenship/reputation.svg
    - assets/images/citizenship/community.svg
    - assets/images/citizenship/planted.svg
    - assets/images/citizenship/age.svg
    - assets/images/citizenship/transaction.svg
    - assets/images/contribution/reputation.svg
    - assets/images/contribution/community.svg
    - assets/images/contribution/planted.svg
    - assets/images/contribution/transaction.svg
    - assets/images/contribution/contribution_detail/petals_left.png
    - assets/images/contribution/contribution_detail/petals_right.png
    - assets/images/seeds_logo.svg
    - assets/images/login/background.png
    - assets/images/login/seeds_light_wallet_logo.svg
    - assets/images/receive/receive_input_seeds.svg
    - assets/images/receive/merchant.svg
    - assets/images/currency_switch_button.svg
    - assets/images/send/telos_logo.png
    - assets/images/transfer/seeds_icon.svg
    - assets/images/transfer/arrow_up.svg
    - assets/animations/forest.json
    - assets/animations/send_animation.json
    - assets/images/google/powered_by_google_on_white.png
    - assets/images/google/powered_by_google_on_non_white.png
    # assets end

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay/SFProDisplay-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SFProDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Black.ttf
          weight: 900
