name: seeds
description: SEEDS Wallet

version: 1.0.9+9

environment:
  sdk: ">=2.6.0 <3.0.0"

analyzer: 
  enable-experiment: extension-methods
   
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  intl_translation:
  cupertino_icons: ^0.1.3
  community_material_icon: ^3.5.95
  flutter_toolbox: ^4.6.2
  http: ^0.12.0+4
  localstorage: ^3.0.1+4
  shared_preferences: ^0.5.6+1
  flutter_secure_storage: ^3.3.2
  local_auth: ^0.6.1
  timeago: ^2.0.26
  url_launcher: ^5.4.1
  cached_network_image: ^2.0.0
  intro_views_flutter:
    git: git://github.com/aagarwal1012/IntroViews-Flutter
  flutter_masked_text: ^0.8.0
  passcode_screen: ^1.0.2
  percent_indicator: ^2.1.1+1
  expandable: ^4.1.2
  flutter_svg: ^0.17.1
  flutter_fluid_slider: ^1.0.2
  firebase_dynamic_links: ^0.5.0+9
  eosdart:
    git:
      url: https://github.com/7flash/eosdart.git
      ref: 12f0d152bbf35ddeea71bc6e337deecb82f86fdf
  eosdart_ecc: ^0.3.2
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.1
  random_words: ^1.0.2
  share: ^0.6.3+5
  provider: ^4.0.4
  basic_utils: ^2.4.8  
  photo_view: ^0.9.1
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.1
  firebase_storage: ^3.1.1
  sentry: ^3.0.1
  hive: ^1.4.1+1
  hive_flutter: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.8.1

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    # assets begin
    # assets/images/*
    - assets/images/error.svg
    - assets/images/explorer.svg
    - assets/images/explorer1.png
    - assets/images/explorer2.png
    - assets/images/explorer3.png
    - assets/images/explorer4.png
    - assets/images/explorer5.png
    - assets/images/explorer_icon.png
    - assets/images/failure.png
    - assets/images/icon_school-bell.png
    - assets/images/launcher_icon.png
    - assets/images/loading.png
    - assets/images/logo_title.png
    - assets/images/no_item_found.svg
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/onboarding4.png
    - assets/images/onboarding5.png
    - assets/images/profile.svg
    - assets/images/seeds-logo-with-text.png
    - assets/images/share.svg
    - assets/images/governance.svg
    - assets/images/community.svg
    - assets/images/harvest.svg
    - assets/images/exchange.svg
    - assets/images/lending.svg
    - assets/images/explorer.svg
    - assets/images/wallet.svg
    - assets/images/profile.svg
    - assets/images/success.svg
    - assets/images/success_circle.png
    - assets/images/logout.svg
    # assets end

  fonts:
    # w100 Thin, the least thick
    # w200 Extra-light
    # w300 Light
    # w400 Normal / regular / plain
    # w500 Medium
    # w600 Semi-bold
    # w700 Bold
    # w800 Extra-bold
    # w900 Black, the most thick
    - family: sfprotext
      fonts:
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Semibold.otf
          weight: 700
    - family: vistolsans
      fonts:
        - asset: assets/fonts/vistolsanslight/VistolSans-Light.otf
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900
